-- AlterTable
ALTER TABLE "prova_aluno" ALTER COLUMN "gcp" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "provas" ALTER COLUMN "nota_maxima" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "nota_minima" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "peso_1" SET DEFAULT 1,
ALTER COLUMN "peso_1" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "peso_2" SET DEFAULT 1,
ALTER COLUMN "peso_2" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "peso_3" SET DEFAULT 1,
ALTER COLUMN "peso_3" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "peso_4" SET DEFAULT 1,
ALTER COLUMN "peso_4" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "peso_5" SET DEFAULT 1,
ALTER COLUMN "peso_5" SET DATA TYPE DOUBLE PRECISION;
