-- AlterTable
ALTER TABLE "provas" ADD COLUMN     "peso_5" INTEGER NOT NULL DEFAULT 1,
ALTER COLUMN "peso_1" SET DEFAULT 1,
ALTER COLUMN "peso_2" SET DEFAULT 1,
ALTER COLUMN "peso_3" SET DEFAULT 1,
ALTER COLUMN "peso_4" SET DEFAULT 1;
